name: hts_plus
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  flutter_load_kit: ^0.0.2
  flutter_screenutil: ^5.9.3
  flutter_localization: ^0.2.0
  flutter_riverpod: ^2.5.1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  dio: ^5.5.0+1
  retrofit: ^4.1.0
  equatable: ^2.0.5
  hive_flutter: ^1.1.0
  smooth_page_indicator: ^1.2.0+3
  readmore: ^3.0.0
  flutter_secure_storage: ^4.2.1
  loading_animation_widget: ^1.2.1
  cached_network_image: ^3.4.1
  google_maps_flutter: ^2.9.0
  flutter_polyline_points: ^2.1.0
  http: ^1.2.2
  webview_flutter: ^4.8.0
  flutter_paystack: ^1.0.5
  

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  retrofit_generator: ^8.1.0
  #very_good_analysis: ^6.0.0
  build_runner: ^2.4.11
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/hts_plus_logo.png"


dependency_overrides:
  intl: ^0.19.0-nullsafety.2
  http: ^0.13.0-nullsafety.2

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logo/


  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100 # FontWeight.w100 for thin
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200 # FontWeight.w200 for extra light
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300 # FontWeight.w300 for light
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400 # FontWeight.w400 for regular
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500 # FontWeight.w500 for medium
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600 # FontWeight.w600 for semi-bold
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700 # FontWeight.w700 for bold
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800 # FontWeight.w800 for extra bold
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900 # FontWeight.w900 for black

